table dim_calendar
	lineageTag: 0c287bd9-1e72-45f9-a4d3-f83121f1f707

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 691c6987-32ef-4799-8625-06328a881b82
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: e6c548b4-5c72-41dd-a0a6-053061e1cb89
			defaultHierarchy: LocalDateTable_3d574bc1-b1f4-4841-9c4f-4cc9a59cd1fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: da3a38b8-124b-4075-a479-8af81964b8fc
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 9deeb75d-7f60-4c51-a6a9-e38341fedbf0
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1f8f772b-d853-4391-bed2-28bd3b07d0c9
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: 9ade3288-7348-469d-adc8-75ff5ee39919
		summarizeBy: none
		sourceColumn: MonthShort
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5c04d05a-5af5-43a8-81f4-586c927bf0e7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: int64
		formatString: 0
		lineageTag: c3147599-bcc0-4b30-a7bd-a68d83dc6d39
		summarizeBy: sum
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: cb2475e8-e3db-4369-aa0c-fe0db8897c50
		summarizeBy: sum
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayOfWeekName
		dataType: string
		lineageTag: c8d5fc1b-d271-480a-9239-2d1f666754fc
		summarizeBy: none
		sourceColumn: DayOfWeekName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayOfWeekShort
		dataType: string
		lineageTag: f84460af-4051-4f50-a386-3644b3151f78
		summarizeBy: none
		sourceColumn: DayOfWeekShort

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: int64
		formatString: 0
		lineageTag: 49e84df8-44c9-44c6-b817-f72ceb237102
		summarizeBy: sum
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	partition dim_calendar = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\vanda\OneDrive\Desktop\Aviation\dim_calendar.csv"), [Delimiter = ",", Columns = 11, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Date", type date}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"MonthName", type text}, {"MonthShort", type text}, {"Quarter", type text}, {"DayOfMonth", Int64.Type}, {"DayOfWeek", Int64.Type}, {"DayOfWeekName", type text}, {"DayOfWeekShort", type text}, {"IsWeekend", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

