table dim_airports
	lineageTag: 20f23094-acb9-4e9f-b585-79e1e97eabaa

	column AirportCode
		dataType: string
		lineageTag: bcf08144-a982-4e36-8466-8f19aca7627b
		summarizeBy: none
		sourceColumn: AirportCode

		annotation SummarizationSetBy = Automatic

	column CityName
		dataType: string
		lineageTag: 359cfcde-7a9d-47ea-a9d2-56a18a01d210
		summarizeBy: none
		sourceColumn: CityName

		annotation SummarizationSetBy = Automatic

	column StateName
		dataType: string
		lineageTag: 2b150c77-6673-4aa0-9e61-38a4be67d259
		summarizeBy: none
		sourceColumn: StateName

		annotation SummarizationSetBy = Automatic

	partition dim_airports = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\vanda\OneDrive\Desktop\Aviation\dim_airports.csv"), [Delimiter = ",", Columns = 3, QuoteStyle = QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"AirportCode", type text}, {"CityName", type text}, {"StateName", type text}})
				in
				  #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

